# Generated by Django 3.1.4 on 2020-12-21 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Descriptions')),
                ('status', models.CharField(choices=[('in_progress', 'IN PROGRESS'), ('stopped', 'STOPPED'), ('finish', 'FINISH')], default='in_progress', max_length=20, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('manager', models.ManyToManyField(related_name='is_manager_in', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('member', models.ManyToManyField(related_name='is_member_in', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('type', models.CharField(choices=[('bugs_errors', 'Bugs/Errors'), ('feature_request', 'Feature Request'), ('questions', 'Questions')], max_length=20, verbose_name='Type')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('assign_to', models.ForeignKey(on_delete=models.SET(main.models.user_deleted), related_name='is_assign_to', to=settings.AUTH_USER_MODEL, verbose_name='Assignment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.project', verbose_name='Project')),
                ('submitter', models.ForeignKey(on_delete=models.SET(main.models.user_deleted), related_name='is_submitter_of', to=settings.AUTH_USER_MODEL, verbose_name='Submitter')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Last Edit')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.ticket', verbose_name='Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path, verbose_name='Attachment')),
                ('attach_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.comment', verbose_name='Attach to')),
            ],
        ),
    ]
