# Generated by Django 3.1.4 on 2020-12-29 13:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, max_length=500, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assign_to',
            field=models.ForeignKey(on_delete=models.SET(main.models.user_deleted), related_name='is_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assignment'),
        ),
    ]
